exc_djangoBlue/exc_djangoProject_blue/djangoApp1/urls.py
from django.urls import path
from djangoApp1 import views

app_name = 'djangoApp1'

urlpatterns = [
    path('tutors/', views.tutorsPage, name='tutorsPage'),
    path('registration/', views.registrationPage, name='registrationPage'),
    path('login/', views.loginPage, name='loginPage'),
    path('logout/', views.logoutPage, name='logoutPage'),
    path('main/', views.mainPage, name='mainPage'),
]

exc_djangoBlue/exc_djangoProject_blue/exc_djangoProject_blue/urls.py
from django.contrib import admin
from django.urls import path, include
from djangoApp1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginPage, name='loginPage'),
    path('djangoApp1/', include('djangoApp1.urls')),
]

exc_djangoBlue/exc_djangoProject_blue/djangoApp1/models.py
from django.db import models
#pylint: disable=imported-auth-user
from django.contrib.auth.models import User

# Create your models here.
class Tutor(models.Model):
    tutor_firstname = models.CharField(max_length=20)
    tutor_lastname = models.CharField(max_length=20)
    tutor_email = models.EmailField()
    tutor_teach_field = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.tutor_firstname} {self.tutor_lastname}"

class Basic_User_Model(models.Model):
    basic_user = models.OneToOneField(User, on_delete=models.CASCADE)

    #Additional Information
    basic_portfolio_site = models.URLField(blank=True)
    basic_profpict = models.ImageField(upload_to="djangoApp1/profile_picts", blank=True)

    def __str__(self):
        return self.basic_user.username

exc_djangoBlue/exc_djangoProject_blue/djangoApp1/forms.py
from django import forms
#pylint: disable=imported-auth-user
from django.contrib.auth.models import User
from djangoApp1.models import Basic_User_Model

class Basic_Form(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "first_name", "last_name", "email", "password")

class Additional_Form(forms.ModelForm):
    class Meta():
        model = Basic_User_Model
        fields = ("basic_portfolio_site", "basic_profpict")

exc_djangoBlue/exc_djangoProject_blue/djangoApp1/views.py
from django.shortcuts import render
from djangoApp1.models import Tutor
from djangoApp1.forms import Basic_Form, Additional_Form

from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def registrationPage(request):
    registered = False

    if request.method == "POST":
        basic_form = Basic_Form(data=request.POST)
        additional_form = Additional_Form(data=request.POST)

        if basic_form.is_valid() and additional_form.is_valid():
            basic = basic_form.save()
            basic.set_password(basic.password)
            basic.save()

            add = additional_form.save(commit=False)
            add.basic_user = basic
            if "basic_profpict" in request.FILES:
                add.basic_profpict = request.FILES["basic_profpict"]

            registered = True
            add.save()

            return HttpResponseRedirect(reverse("loginPage"))
        else:
            print(basic_form.errors, additional_form.errors)
    else:
        basic_form = Basic_Form()
        additional_form = Additional_Form()

    context_dict = {"registered":registered, "basic_form":basic_form, "additional_form":additional_form}
    return render(request, "djangoApp1/registrationPage.html", context=context_dict)

def loginPage(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("djangoApp1:mainPage"))
            else:
                return HttpResponse("Your account is not active!")
        else:
            return HttpResponse(f"Invalid login!\nInserted username: {username}\nInserted password: {password}")
    else:
        return render(request, "djangoApp1/loginPage.html", context={})

@login_required
def logoutPage(request):
    logout(request)
    return render(request, "djangoApp1/logoutPage.html", context={})

@login_required
def mainPage(request):
    return render(request, "djangoApp1/mainPage.html", context={})

@login_required
def tutorsPage(request):
    tutor_data = Tutor.objects.order_by("tutor_firstname")
    context_dict = {"tutor_data":tutor_data}
    return render(request, "djangoApp1/tutorsPage.html", context=context_dict)

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/base_log.html
<!DOCTYPE HTML>
{% load static %}
<html>
    <head>
        <meta charset = "utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'djangoApp1/css/base_log_master.css' %}">
        {% block head_block %}
            <!--Title and css goes here-->
        {% endblock %}
    </head>
    <body style="height: 100%;">
        {% block body_block %}
        <!-- Main contents goes here -->
        {% endblock %}

        <footer id="footer_log">
            <div class="container-fluid">
                <label for="facebook"><img class="image_footer" src="{% static 'djangoApp1/images/facebook.png' %}" alt="Picture was not found"></label>
                <a id="facebook" href="https://www.facebok.com">Edukas_official</a>

                <label for="instagram"><img class="image_footer" src="{% static 'djangoApp1/images/instagram.png' %}" alt="Picture was not found"></label>
                <a id="instagram" href="https://www.instagram.com">@Edukas_official</a>

                <label for="whatsapp"><img class="image_footer" src="{% static 'djangoApp1/images/whatsapp.png' %}" alt="Picture was not found"></label>
                <a id="whatsapp" href="https://www.whatsapp.com">081728483756</a>
            </div>
        </footer>
    </body>
    {% block script_block %}
        <!-- Scripts goes here -->
    {% endblock %}
</html>

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/base_main.html
<!DOCTYPE HTML>
{% load static %}
<html>
    <head>
        <meta charset = "utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'djangoApp1/css/base_main_master.css' %}">
        {% block head_block %}

        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="{% url 'admin:index' %}">Admin</a>
            <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav mr-auto">
                    <a class="nav-link" href="{% url 'djangoApp1:mainPage' %}">Home</a>
                    <a class="nav-link" href="{% url 'djangoApp1:tutorsPage' %}">Tutors</a>
                    <a class="nav-link" href="#">Courses</a>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'djangoApp1:logoutPage' %}">Log-out</a>
                </div>
            </div>
        </nav>

        {% block body_block %}

        {% endblock %}

        <footer id="footer_log">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-lg-4 col-md-12 d-flex justify-content-start align-items-center">
                                <label for="facebook"><img class="image_footer" src="{% static 'djangoApp1/images/facebook.png' %}" alt="Picture was not found"></label>
                                <a id="facebook" href="https://www.facebok.com">Edukas_official</a>
                            </div>
                            <div class="col-lg-4 col-md-12 d-flex justify-content-start align-items-center">
                                <label for="instagram"><img class="image_footer" src="{% static 'djangoApp1/images/instagram.png' %}" alt="Picture was not found"></label>
                                <a id="instagram" href="https://www.instagram.com">@Edukas_official</a>
                            </div>
                            <div class="col-lg-4 col-md-12 d-flex justify-content-start align-items-center">
                                <label for="whatsapp"><img class="image_footer" src="{% static 'djangoApp1/images/whatsapp.png' %}" alt="Picture was not found"></label>
                                <a id="whatsapp" href="https://www.whatsapp.com">081728483756</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
    {% block script_block %}

    {% endblock %}
</html>

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/loginPage.html
{% extends "djangoApp1/base_log.html" %}
{% load static %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'djangoApp1/css/loginPage_master.css' %}">
<title>Log in</title>
{% endblock %}

{% block body_block %}
     <div class="container main_container d-flex justify-content-center align-items-center">
          <div class="jumbotron main_jumbotron">
                <div class="row">
                      <div class="col-md-12 d-flex align-items-center picture_login">
                           <img id="user_login_pict" src="{% static 'djangoApp1\images\user_login.png' %}" alt="Picture was not found">
                           <h3>Log In</h3>
                      </div>
                      <hr class="my-4">
                      <div class="col-md-12">
                           <form action="" method="post">
                                {% csrf_token %}
                                <input type="text" name="username" placeholder="Username">
                                <input type="password" name="password" placeholder="Password">
                                <input type="submit" value="Log in">
                           </form>
                           <div class="container create_account d-flex justify-content-center align-items-center">
                                <a><em>Not registered yet?</em></a><br>
                                <a href="{% url 'djangoApp1:registrationPage' %}">Create Account!</a>
                           </div>
                      </div>
                </div>
           </div>
     </div>
{% endblock %}

{% block script_block %}

{% endblock %}

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/logoutPage.html
{% extends "djangoApp1/base_log.html" %}

{% block head_block %}
    <title>Log out</title>
    <style>
        .container_logout{
            height: 100%;
        }

        .jumbotron_logout{
            flex-direction: column;
        }
    </style>
{% endblock %}

{% block body_block %}
    <div class="container d-flex justify-content-center align-items-center container_logout">
        <div class="jumbotron d-flex justify-content-center align-items-center jumbotron_logout">
            <h1>Thank you for your visit!</h1>
            <p><em>Return to <a href="{% url 'djangoApp1:loginPage' %}">Log in page</a></em></p>
        </div>
    </div>
{% endblock %}

{% block script_block %}

{% endblock %}

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/mainPage.html
{% extends "djangoApp1/base_main.html" %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="{% static 'djangoApp1/css/mainPage_master.css' %}">
    <title>Edukas</title>
    <style>
        .container_1{
            background-image: url("{% static 'djangoApp1/images/background_cont1.jpg' %}");
        }

        .container_2{
            background-image: url("{% static 'djangoApp1/images/background_cont2.jpg' %}");
        }
    </style>
{% endblock %}

{% block body_block %}
    <div class="container-fluid container_1">
        <div class="row">
            <div class="col-md-6">
                <div class="jumbotron jumbotron_1">
                    <h1 class="display-4">Edukas</h1>
                    <p class="lead"><em>~Where incredible journey of education began~</em></p>
                    <hr class="my-4">
                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ex aliquam quaerat laudantium blanditiis explicabo temporibus nemo dicta commodi repellendus labore!</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid container_2">
        <h2 class="display-4 text_align_center">What do we offer?</h2>
        <div class="row col_holder">
            <div class="col-md-4 col-12 card_holder d-flex justify-content-center align-items-center">
                <div class="card" style="width: 18rem;">
                    <img class="card_image" src="{% static 'djangoApp1/images/card_background.jpg' %}" alt="Picture was not found">
                    <div class="card-body">
                        <h5 class="card-title">Sample Header</h5>
                        <p class="card-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea repellat pariatur enim iusto, cumque eos nobis quis! Cupiditate, in dolor dolore sit nihil, amet maxime repudiandae cumque, nobis nisi minima!</p>
                        <a class="btn btn-info" href="#">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-12 card_holder d-flex justify-content-center align-items-center">
                <div class="card" style="width: 18rem;">
                    <img class="card_image" src="{% static 'djangoApp1/images/card_background.jpg' %}" alt="Picture was not found">
                    <div class="card-body">
                        <h5 class="card-title">Sample Header</h5>
                        <p class="card-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea repellat pariatur enim iusto, cumque eos nobis quis! Cupiditate, in dolor dolore sit nihil, amet maxime repudiandae cumque, nobis nisi minima!</p>
                        <a class="btn btn-info" href="#">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-12 card_holder d-flex justify-content-center align-items-center">
                <div class="card" style="width: 18rem;">
                    <img class="card_image" src="{% static 'djangoApp1/images/card_background.jpg' %}" alt="Picture was not found">
                    <div class="card-body">
                        <h5 class="card-title">Sample Header</h5>
                        <p class="card-text">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea repellat pariatur enim iusto, cumque eos nobis quis! Cupiditate, in dolor dolore sit nihil, amet maxime repudiandae cumque, nobis nisi minima!</p>
                        <a class="btn btn-info" href="#">Learn More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script_block %}

{% endblock %}

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/registrationPage.html
{% extends "djangoApp1/base_log.html" %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="{% static 'djangoApp1/css/registrationPage_master.css' %}">
    <title>Registration</title>
{% endblock %}

{% block body_block %}
    <div class="contaier">
        <div class="jumbotron">
            <h1>Welcome to the Registration Page</h1>
            <h3>Please fill the form below</h3>

            {% if not registered %}
                <form method="post">
                    {% csrf_token %}
                    {{ basic_form.as_p }}
                    {{ additional_form.as_p }}

                    <input type="submit" class="btn btn-primary" value="Register">
                </form>
            {% else %}
                <h1>Thank your for your registration!</h1>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block script_block %}

{% endblock %}

exc_djangoBlue/exc_djangoProject_blue/templates/djangoApp1/tutorsPage.html
{% extends "djangoApp1/base_main.html" %}
{% load static %}

{% block head_block %}
    <link rel="stylesheet" href="{% static 'djangoApp1/css/tutorsPage_master.css' %}">
    <title>Tutors</title>
    <style>
        .container_1{
            background-image: url("{% static 'djangoApp1/images/background_cont1.jpg' %}");
        }
    </style>
{% endblock %}

{% block body_block %}
    <div class="container-fluid container_1">
        <h1 class="display-4 text_align_center header_1">Below is our list of tutors</h1>
        {% if tutor_data %}
            <div class="container">
                <table>
                    <thead>
                        <th class="text_align_center">First Name</th>
                        <th class="text_align_center">Last Name</th>
                        <th class="text_align_center">Email</th>
                        <th class="text_align_center">Teach Field</th>
                    </thead>
                    {% for tutor in tutor_data %}
                        <tr>
                            <td>{{ tutor.tutor_firstname }}</td>
                            <td>{{ tutor.tutor_lastname }}</td>
                            <td>{{ tutor.tutor_email }}</td>
                            <td>{{ tutor.tutor_teach_field }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block script_block %}
    <script>
        window.onload = function(){
            all_row = $("tr")
            for(let index=1; index<all_row.length-1; index++){
                if(all_row.eq(index).css("background-color") == "rgb(247, 247, 245)"){
                    all_row.eq(index+1).css("background-color", "rgb(77, 160, 219)")
                }
            }
        }
    </script>
{% endblock %}